# Codecov Konfiguration
# Referenz: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: false   # Kommentar kann erscheinen auch wenn Job noch läuft
  max_report_age: 24          # Stunden

coverage:
  precision: 2
  round: down
  range: "50...90"            # Visuale Farbskala
  status:
    project:
      default:
        target: auto           # Codecov wählt smartes Ziel (meist Durchschnitt Historie)
        threshold: 2%          # Bis zu 2% Rückgang toleriert
        informational: false
    patch:
      default:
        target: auto
        threshold: 2%
        informational: false

ignore:
  - "docs/**"
  - "benchmarks/**"
  - "site/**"
  - "paper/**"
  - "__pycache__/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true        # Kein neuer Kommentar, wenn Coverage gleich bleibt

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Optional für zukünftige Erweiterungen
# github_checks:
#   annotations: true
